apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
spec:
  addresses:
  - 192.168.3.1-192.168.3.254
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: opnsense-peer
spec:
  myASN: 64513
  peerASN: 64512
  peerAddress: 192.168.0.1
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-advertisement
