apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
spec:
  addresses:
  - 192.168.3.16-192.168.3.254
---
apiVersion: metallb.io/v1beta1
kind: BFDProfile
metadata:
  name: opnsense-bfd
  namespace: metallb-system
spec:
  receiveInterval: 380
  transmitInterval: 270
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: opnsense-peer
spec:
  myASN: 64513
  peerASN: 64512
  peerAddress: 192.168.0.1
  bfdProfile: opnsense-bfd
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-advertisement
