apiVersion: v1
kind: Secret
metadata:
    name: tailscale-secret-values
    namespace: tailscale
type: Opaque
data:
    values.yaml: ENC[AES256_GCM,data:nw6Tf0+x2b7NaU6t754JoCKfWZ4dPA3DEDFQlWMP4DTlqwpQ0dih+VUYck9HeaXQKG4qxbj2bqUOnK6U4qr4I5ugTnMZy2vJVw2u1ftGTD/aIDF86c+NHtlAw0GwYAdR1JVp6IezMfD9jQ15AjDUQhCm02e8tQFR/Q==,iv:oaeKf7kTy6p5iE6EjFhNuD4WNvzrhWrov78tGBS73gM=,tag:ZcxB+q+HglccerUeMm5mFg==,type:str]
sops:
    age:
        - recipient: age1w67tp7vumngt0358xh63ayhlwkqc04tc7qk0nu6a7weg6arlqyxsrrexy6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbnNYOE5QbFVMeXlpajA5
            K3pUZ3dYbThQQlRRWkVDWXY5eGplT0QxZEhNCmltbEtaaHZORkMvYzZTNDZPMitl
            VjBiVVE2d1BsZnJzN0gxeXBkN1VUS2sKLS0tIDRsVmcwZ0NYN3JlckdXczBRWEtt
            NEpWMDEvSzk5T2llN25YVlZydWFZNEUKObFrvO4vZm9m6EzikaoiRndnM2nGMhOP
            O2N+Sk/5rAg9tSR+ipuJjCaSeza/pN+9twoR1hudrIAfnVITVopfOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T06:46:21Z"
    mac: ENC[AES256_GCM,data:1ymjeZ7Zli6+ISP8zmAf4+QNwaK/0uBqBf76lVTHrU+Aq5cnDMISITigh0Wg0pGRKf+UKwC/B55z3s6I9itvMqVk77UbSOB+ITAY7Bok0CXYAWOif35LrgC7DXtSSjWrwGXMPZ4jITD/1fU9nSOw1JKODbPf3F0X4zTnv/wihrE=,iv:AugWYBeNUJKeSUi0c9uMZ3Gylzn5Yv6LBzb85Epir30=,tag:K95WqixlYYnNtjfBUmZ8GA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
