apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: mc
  name: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mc
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: mc
    spec:
      containers:
      - env:
        - name: EULA
          value: "TRUE"
        - name: OPS
          value: ninjawarrior1337
        - name: MEMORY
          value: "2684M"
        image: ghcr.io/itzg/minecraft-server:2026.1.3-java25
        name: mc
        ports:
        - containerPort: 25565
          protocol: TCP
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /data
          name: mc-data
        resources:
          requests:
            memory: "2G"
            cpu: "500m"
          limits:
            memory: "3G"
            cpu: "2"
        readinessProbe:
          tcpSocket:
            port: 25565
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          tcpSocket:
            port: 25565
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 10
          successThreshold: 1
          timeoutSeconds: 1
      restartPolicy: Always
      volumes:
      - name: mc-data
        persistentVolumeClaim:
          claimName: mc-data
